### ISSUE TITLE
OTALog doesn't work

### ISSUE THREAD

**Issue by Isa001** [mysensors/MySensors#1012]
In MyOTALogging.cpp

OTALog(...) can not work correctly.
The message is sent 4 times.
Moreover, characters string is unreadable on the debug serial output.

`Line 39: #ifdef vsnprintf_P`

replace by `#ifdef __AVR__`

Delete from Line 71 to Line 78

```
// Send package
	for (int pos = 0; pos<n; pos+=MAX_PAYLOAD) {
		uint8_t length = strlen(&fmtBuffer[pos]);
		if (length>MAX_PAYLOAD) {
			length = MAX_PAYLOAD;
		}
		(void)_sendRoute(msg.set((char*)&fmtBuffer[pos]));
	}
```

replace by

`(void)_sendRoute(msg.set(fmtBuffer));`

*************************************************

In OTALogPrintPrefix() function

`Line 95: #ifdef vsnprintf_P`

replace by `#ifdef __AVR__`

**Comment by d00616** [comment]
@Isa001 Sorry, this doesn't fix the problem. The code filling the buffer is a problem, when a PSTR is given on AVR controllers. "OTALog(0, true, "My Message");" or "OTALog(0, true, "%d", millis());" works fine.

The code formating the send buffer is taken from AVR debug message code, but it fails in that case. I have no idea why, maybe the MCU is running out of memory. So OTA Logging is only compatible with 32 Bit MCUs.

Sorry, I can't help here.
