### ISSUE TITLE
receiveTime() function prototype changed

### ISSUE THREAD

**Issue by myachniy** [mysensors/MySensors#1015]
Hello.

As you've changed the prototype of the receiveTime(unsigned long) to receiveTime(uint32_t) the old code that defines receiveTime(unsigned long){...} function won't work any more since **receiveTime(unsigned long)** and **receiveTime(uint32_t)** are two different functions for the compiler.

Roll the prototype back or correct the [API](https://www.mysensors.org/download/sensor_api_20) with new prototype.

Best regards,
Maxim.

**Comment by mfalkvidd** [comment]
Thanks for noticing this. I've updated the API page. feel free to reopen with comment in case something still is missing.
