### ISSUE TITLE
ATmega168 does not have the SIGRD bit available

### ISSUE THREAD

**Issue by mitchmitchell** [mysensors/MySensors#1081]
I was able to compile NodeManager and MySensors for the ATmega168 on an original Arduino Diecimila with the ATmega168 processor and a DHT22 sensor -- there is actually enough memory on the little chip to handle it (can't do the DS18B20 sensors unfortunately, takes too much space).   I don't know if anyone is actually using boards with the ATmega168 but I thought I'd open this just to document what was needed, please close it if no interest.

added #if `!defined(__AVR_ATmega168__)` around the one piece of code that uses the register bit, since the 168 does not have the bit (the 168P apparently does however).  Keep the unique_ID all MY_HWID_PADDING_BYTEs since there is no unique id.

At line 246 in MyHwAVR.cpp

bool hwUniqueID(unique_id_t* uniqueID)
{
	// padding
	(void)memset(uniqueID, MY_HWID_PADDING_BYTE, sizeof(unique_id_t));
	// no unique ID for non-PB AVR, use HW specifics for diversification
	#if `!defined(__AVR_ATmega168__)`
	*((uint8_t*)uniqueID) = boot_signature_byte_get(0x00);
	*((uint8_t*)uniqueID + 1) = boot_signature_byte_get(0x02);
	*((uint8_t*)uniqueID + 2) = boot_signature_byte_get(0x04);
	*((uint8_t*)uniqueID + 3) = boot_signature_byte_get(0x01); //OSCCAL
	#endif
	// ATMEGA328PB specifics, has unique ID
	//for(uint8_t idx = 0; idx < 10; idx++) {
	//	*((uint8_t*)uniqueID + 4 + idx) = boot_signature_byte_get(0xE + idx);
	//}
	return false;	// false, since no unique ID returned
}

**Comment by mfalkvidd** [comment]
Reference to forum thread (so we don't spend unnecessary time discussing in one place something that might have already been covered in the other place)
https://forum.mysensors.org/topic/9134/new-compile-error-for-pro-mini-3-3v-168/
