### ISSUE TITLE
Log parser missing messages

### ISSUE THREAD

**Issue by mfalkvidd** [mysensors/MySensors#1083]
The following messages can not be decoded by the log parser:
```
26415 TSM:FAIL:DIS
41037 MCO:SLP:MS=1790000	
41039 TSF:TDI:TSL
```
Log example [here](https://www.mysensors.org/build/parser?log=0%20MCO%3ABGN%3AINIT%20NODE%2CCP%3DRNNNA---%2CVER%3D2.2.0%0A4%20TSM%3AINIT%0A4%20TSF%3AWUR%3AMS%3D30000%0A12%20TSM%3AINIT%3ATSP%20OK%0A14%20TSF%3ASID%3AOK%2CID%3D11%0A16%20TSM%3AFPAR%0A53%20TSF%3AMSG%3ASEND%2C11-11-255-255%2Cs%3D255%2Cc%3D3%2Ct%3D7%2Cpt%3D0%2Cl%3D0%2Csg%3D0%2Cft%3D0%2Cst%3DOK%3A%0A2060%20!TSM%3AFPAR%3ANO%20REPLY%0A2062%20TSM%3AFPAR%0A2099%20TSF%3AMSG%3ASEND%2C11-11-255-255%2Cs%3D255%2Cc%3D3%2Ct%3D7%2Cpt%3D0%2Cl%3D0%2Csg%3D0%2Cft%3D0%2Cst%3DOK%3A%0A4106%20!TSM%3AFPAR%3ANO%20REPLY%0A4108%20TSM%3AFPAR%0A4145%20TSF%3AMSG%3ASEND%2C11-11-255-255%2Cs%3D255%2Cc%3D3%2Ct%3D7%2Cpt%3D0%2Cl%3D0%2Csg%3D0%2Cft%3D0%2Cst%3DOK%3A%0A6152%20!TSM%3AFPAR%3ANO%20REPLY%0A6154%20TSM%3AFPAR%0A6191%20TSF%3AMSG%3ASEND%2C11-11-255-255%2Cs%3D255%2Cc%3D3%2Ct%3D7%2Cpt%3D0%2Cl%3D0%2Csg%3D0%2Cft%3D0%2Cst%3DOK%3A%0A8198%20!TSM%3AFPAR%3AFAIL%0A8200%20TSM%3AFAIL%3ACNT%3D1%0A8202%20TSM%3AFAIL%3ADIS%0A8204%20TSF%3ATDI%3ATSL%0A18206%20TSM%3AFAIL%3ARE-INIT%0A18208%20TSM%3AINIT%0A18214%20TSM%3AINIT%3ATSP%20OK%0A18219%20TSF%3ASID%3AOK%2CID%3D11%0A18221%20TSM%3AFPAR%0A18257%20TSF%3AMSG%3ASEND%2C11-11-255-255%2Cs%3D255%2Cc%3D3%2Ct%3D7%2Cpt%3D0%2Cl%3D0%2Csg%3D0%2Cft%3D0%2Cst%3DOK%3A%0A20267%20!TSM%3AFPAR%3ANO%20REPLY%0A20269%20TSM%3AFPAR%0A20305%20TSF%3AMSG%3ASEND%2C11-11-255-255%2Cs%3D255%2Cc%3D3%2Ct%3D7%2Cpt%3D0%2Cl%3D0%2Csg%3D0%2Cft%3D0%2Cst%3DOK%3A%0A22315%20!TSM%3AFPAR%3ANO%20REPLY%0A22317%20TSM%3AFPAR%0A22353%20TSF%3AMSG%3ASEND%2C11-11-255-255%2Cs%3D255%2Cc%3D3%2Ct%3D7%2Cpt%3D0%2Cl%3D0%2Csg%3D0%2Cft%3D0%2Cst%3DOK%3A%0A24363%20!TSM%3AFPAR%3ANO%20REPLY%0A24365%20TSM%3AFPAR%0A24401%20TSF%3AMSG%3ASEND%2C11-11-255-255%2Cs%3D255%2Cc%3D3%2Ct%3D7%2Cpt%3D0%2Cl%3D0%2Csg%3D0%2Cft%3D0%2Cst%3DOK%3A%0A26411%20!TSM%3AFPAR%3AFAIL%0A26413%20TSM%3AFAIL%3ACNT%3D2%0A26415%20TSM%3AFAIL%3ADIS%0A26417%20TSF%3ATDI%3ATSL%0A30007%20MCO%3ABGN%3ASTP%0A30009%20MCO%3ABGN%3AINIT%20OK%2CTSP%3D0%0A30011%20MCO%3ASLP%3AMS%3D1000%2CSMS%3D0%2CI1%3D255%2CM1%3D255%2CI2%3D255%2CM2%3D255%0A30017%20!MCO%3ASLP%3ATNR%0A31019%20!MCO%3ASND%3ANODE%20NOT%20REG%0A31023%20!MCO%3ASND%3ANODE%20NOT%20REG%0A31027%20!TSF%3ASND%3ATNR%0A31029%20MCO%3ASLP%3AMS%3D1800000%2CSMS%3D0%2CI1%3D255%2CM1%3D255%2CI2%3D255%2CM2%3D255%0A31035%20!MCO%3ASLP%3ATNR%0A36421%20TSM%3AFAIL%3ARE-INIT%0A36423%20TSM%3AINIT%0A36429%20TSM%3AINIT%3ATSP%20OK%0A36433%20TSF%3ASID%3AOK%2CID%3D11%0A36435%20TSM%3AFPAR%0A36472%20TSF%3AMSG%3ASEND%2C11-11-255-255%2Cs%3D255%2Cc%3D3%2Ct%3D7%2Cpt%3D0%2Cl%3D0%2Csg%3D0%2Cft%3D0%2Cst%3DOK%3A%0A38483%20!TSM%3AFPAR%3ANO%20REPLY%0A38486%20TSM%3AFPAR%0A38522%20TSF%3AMSG%3ASEND%2C11-11-255-255%2Cs%3D255%2Cc%3D3%2Ct%3D7%2Cpt%3D0%2Cl%3D0%2Csg%3D0%2Cft%3D0%2Cst%3DOK%3A%0A40534%20!TSM%3AFPAR%3ANO%20REPLY%0A40536%20TSM%3AFPAR%0A40572%20TSF%3AMSG%3ASEND%2C11-11-255-255%2Cs%3D255%2Cc%3D3%2Ct%3D7%2Cpt%3D0%2Cl%3D0%2Csg%3D0%2Cft%3D0%2Cst%3DOK%3A%0A41037%20MCO%3ASLP%3AMS%3D1790000%0A41039%20TSF%3ATDI%3ATSL%0A)

**Comment by henrikekblad** [comment]
Fixed
