### ISSUE TITLE
hwCPUFrequency() in AVR/MyHwAVR.cpp

### ISSUE THREAD

**Issue by Isa001** [mysensors/MySensors#1086]
Why not save TCCR1B register as well ?

I use timer1 as comparator without prescaller.
But when I call hwCPUFrequency() my sketch doesn't work anymore.
hwCPUFrequency() uses timer1 and TCCR1B is not restored.

Thanks for the great work !

**Comment by mfalkvidd** [comment]
TCCR1B was supposedly saved by https://github.com/mysensors/MySensors/pull/1059 when  https://github.com/mysensors/MySensors/issues/1032 was fixed. So this might be fixed in the development branch. However, I am unable to find a reference to TCCR1B in #1059 so I am not sure.
