### ISSUE TITLE
Rename "soft ack" to "echo"

### ISSUE THREAD

**Issue by mfalkvidd** [mysensors/MySensors#1103]
The send() functions (send(), present(), sendSketchInfo(), sendBatteryLevel() and maybe more) have a parameter called ack, which often is confused with what might be called "hardware ack" (see https://forum.mysensors.org/post/34263 for one of many lengthy discussions).

Suggestion: rename the parameter to echo. That should make it harder to confuse with the hardware ack, and reflects more accurately what will actually happen:

> the final destination will echo back the contents of the message, triggering the receive() function on the original node with a copy of the message, with message.isAck() set and sender/destination switched.

NOTE: We'll need to rename message.isAck() to message.isEcho() (keeping Ack in the name will be confusing) but if the isAck function is not present, existing sketches will become broken. We probably don't want to break sketches in a minor release. Maybe we can deprecate isAck and add isEcho for a smoother transition.

**Comment by flatsiedatsie** [comment]
Should .isAck() now be renamed to .isEcho() in node code?

**Comment by mfalkvidd** [comment]
@flatsiedatsie yes
![image](https://user-images.githubusercontent.com/893502/58641525-a4839600-82fb-11e9-9640-6e282c66bf6e.png)

Temporary staging url for the documentation before this PR is merged: https://ci.mysensors.org/job/MySensors/job/MySensors/job/PR-1292/7/Doxygen_20HTML/MyMessage_8h.html#a8f286dd914ce8dda5a5795d9cbb74b44
