### ISSUE TITLE
OTA updates slow on RPI

### ISSUE THREAD

**Issue by Swiftnesses** [mysensors/MySensors#1150]
Good day,

After a full day of testing I can confirm that OTA node updates via the RPI gateway are extremely slow (1-2 stream messages per few seconds). Reverting back to either the serial or ethernet gateway resolves the issue (constant stream of messages).

All configs were the same, i.e version, channel, power etc etc.

**Comment by mfalkvidd** [comment]
Could you share the configure command used for the gateway?

**Comment by Swiftnesses** [comment]
./configure --my-transport=nrf24 --my-rf24-channel=125 --my-rf24-pa-level=RF24_PA_MAX --my-rf24-irq-pin=15 --extra-cxxflags="-DMY_OTA_LOG_RECEIVER_FEATURE"

**Comment by Swiftnesses** [comment]
Guys, it's not just the Pi, it's all gateways - the issue coincided with me updating to 2.3.0 branch. Rolling back to 2.2.0 immediately fixes it. @tekka007

**Comment by Swiftnesses** [comment]
Update: After another few hours sitting on the floor with wires going crazy, it seems it's related to this commit:

https://github.com/mysensors/MySensors/commit/2994d83e53cda2867a80ff413575938ecd6d3ab2

Replacing this file with the one from 2.2.0 causes ITA updates to resume full speed!

**Comment by Swiftnesses** [comment]
Confirmed, with the file replaced, my Gateway (also tried other variants) is now working perfect!

**Comment by Swiftnesses** [comment]
Another update - while replacing the file fixes the issue with the slow packets on the PA+LNA radio - it also seems to cause the gateway to fail after sometime - I assume that's because a simple file replace isn't the right way of fixing this, reverting back to 2.2.0 for now.

**Comment by marceloaqno** [comment]
@Swiftnesses thanks for the detailed feedback.

**Comment by Swiftnesses** [comment]
Any news on this guys?

**Comment by tekka007** [comment]
@Swiftnesses Yes, #1189 fixes an issue with certain RF24 PA + LNA modules. Please try with the current dev branch

**Comment by Swiftnesses** [comment]
@tekka007 Just tried it, seems the discover button in MYSController no longer works with the dev branch?

**Comment by Swiftnesses** [comment]
Not working well for me at all, discover doesn't work and request presentation only provides version and one of the sensors (node has 3). Consistent behaviour.

**Comment by tekka007** [comment]
I_DISCOVER messaging fixed in #1205

**Comment by Swiftnesses** [comment]
@tekka007 That fixed it, a reboot of the nodes also fixed the presentation reporting issue!
