### ISSUE TITLE
 Move functions from transport to architecture

### ISSUE THREAD

**Issue by spectrespc** [mysensors/MySensors#1232]
For more simple addition of new platforms, maybe it is worth to transfer special functions to platform architecture?
An example below and in my [fork](https://github.com/spectrespc/MySensors/commit/101724584c4d00cd5dc8be04c852bd6baf659dec)

RF24_SPI.transfer(cmd); to hwSPItransfer(cmd);
...
and etc...

**Comment by mfalkvidd** [comment]
Tekka is working on adding this. Reference: 
https://github.com/mysensors/MySensors/pull/1234

**Comment by spectrespc** [comment]
Ok! Good. Close it.
