### ISSUE TITLE
Compile error when using rocketscream/Low-Power

### ISSUE THREAD

**Issue by andreas-bulling** [mysensors/MySensors#1267]
I am trying to use the Low-Power library from RocketScream:
https://github.com/rocketscream/Low-Power

But I see the following compile error when only adding `#include <LowPower.h>`:

```
libraries/Low-Power-master/LowPower.cpp.o (symbol from plugin): In function `LowPowerClass::idle(period_t, adc_t, timer2_t, timer1_t, timer0_t, spi_t, usart0_t, twi_t)':
(.text+0x0): multiple definition of `__vector_6'
sketch/sensor_mysensor.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board Arduino Pro or Pro Mini.
```

**Comment by mfalkvidd** [comment]
MySensors provides a sleep function that covers most low power scenarios. If sleep doesn't cover your scenario, implementing 
https://github.com/mysensors/MySensors/issues/415 might be a solution.
Closing this issue. #415 covers trying to make MySensors compatible with the low-power library.
