### ISSUE TITLE
MySigningAtsha204Soft bug in Gateway mode 

### ISSUE THREAD

**Issue by YuanWujin** [mysensors/MySensors#1326]
I use one ESP8266 module as the mysensors MQTT gateway,and another ESP8266 module as a mysensors client device.

I used MY_SECURITY_SIMPLE_PASSWD "xxxxx",and MySigningAtsha204Soft to encrypto signature and password.

This gateway does not use MY_SIGNING_NODE_WHITELISTING.

I  connected the mysensors gateway to the Domoticz server,and setup the client devices UI succesfully. 

When I send a msg from client to gateway, the gateway works OK.
But when I tried to control Domoticz UI to change mysensors client devices status,the ESP8266 mysensors client encountered a error :
```
!SGN:VER:FAIL
!TSF:MSG:SIGN VERIFY FAIL
```
The version of Mysensors I used is 2.3.1 .

I modified the source code to fix this bug like this (in Mysensors/core/MySigningAtsha204Soft.cpp)(I added the Macro MY_SIGNING_NODE_WHITELISTING to hide DO_WHITELIST() ):

```

bool signerAtsha204SoftSignMsg(MyMessage &msg)
{
	// If we cannot fit any signature in the message, refuse to sign it
	if (mGetLength(msg) > MAX_PAYLOAD-2) {
		SIGN_DEBUG(PSTR("!SGN:BND:SIG,SIZE,%" PRIu8 ">%" PRIu8 "\n"), mGetLength(msg),
		           MAX_PAYLOAD-2); //Message too large
		return false;
	}

	// Calculate signature of message
	mSetSigned(msg, 1); // make sure signing flag is set before signature is calculated
	signerCalculateSignature(msg, true);
#ifdef MY_SIGNING_NODE_WHITELISTING
	if (DO_WHITELIST(msg.destination)) {
		// Salt the signature with the senders nodeId and the (hopefully) unique serial The Creator has
		// provided. We can reuse the nonce buffer now since it is no longer needed
		(void)memcpy((void *)_signing_nonce, (const void *)_signing_hmac, 32);
		_signing_nonce[32] = msg.sender;
		(void)memcpy((void *)&_signing_nonce[33], (const void *)_signing_node_serial_info, 9);
		SHA256(_signing_hmac, _signing_nonce, 32+1+9);
		SIGN_DEBUG(PSTR("SGN:BND:SIG WHI,ID=%" PRIu8 "\n"), msg.sender);
#ifdef MY_DEBUG_VERBOSE_SIGNING
		buf2str(_signing_node_serial_info, 9);
		SIGN_DEBUG(PSTR("SGN:BND:SIG WHI,SERIAL=%s\n"), printStr);
#endif
	}
#endif
	// Overwrite the first byte in the signature with the signing identifier
	_signing_hmac[0] = SIGNING_IDENTIFIER;

	// Transfer as much signature data as the remaining space in the message permits
	(void)memcpy((void *)&msg.data[mGetLength(msg)], (const void *)_signing_hmac,
	             MIN(MAX_PAYLOAD-mGetLength(msg), 32));

	return true;
}

```

Now the gateway and devices work OK.

**Comment by fallberg** [comment]
Thanks for the report. I suspect it is due to "garbage" in the security related settings in eeprom which indicate whitelisting requirements for the node in question.
Or that you at some point did use whitelisting and the GW marked the node as user of whitelisting. That setting will be sticky unless weak security is enabled.
Your suggested change looks reasonable so please file it as a pull request.
