### ISSUE TITLE
Fix ESP8266/ESP32 "ISR not in IRAM" runtime exception

### ISSUE THREAD

**Issue by Yveaux** [mysensors/MySensors#1334]
Refer to: https://forum.mysensors.org/topic/10581/isr-not-in-iram-error

ESP interrupt handlers shall be prefixed with "ICACHE_RAM_ATTR"

**Comment by mfalkvidd** [comment]
Since this attribute was not required in earlier board versions, maybe we need to check if the adding the attribute will break things for older board versions.

**Comment by mfalkvidd** [comment]
The incompatible change in the esp8266 board definition was introduced in v2.5.1, so a workaround is to use board version 2.5.0 or earlier.

Reference: https://github.com/esp8266/Arduino/pull/6141

**Comment by mfalkvidd** [comment]
Also see https://groups.google.com/a/arduino.cc/forum/m/#!topic/developers/56VPC9t2MPc which discusses how to generalize the ICACHE_RAM_ATTR requirement. It mentions thatt all functions called from within an ISR also needs the attribute. If that is true, a lot of funcrions will be affected.

**Comment by sp9auv** [comment]
Problem with ISR not IRAM in a WEMOS or ARDUION is that  memory for  that handle ISR interrupt must be reserved in a section DECLARATION for values  in this way for example 
**void ICACHE_RAM_ATTR ServiceLimitSwitchUpperShield_12_D6();**   
 // There are solved for  ATTACHINTERRUPT - you must **declare this before function SETUP (very important )** 
In a section SETUP you can define 
**attachInterrupt(digitalPinToInterrupt(12), ServiceLimitSwitchUpperShield_12_D6 , FALLING );**
      
The method ServiceLimitSwitchUpperShield_12_D6   define for example
**[[ichache_IRAM_ATTR]] 
void ServiceLimitSwitchUpperShield_12_D6()** 

Take attention what memory is need for your souce code . This value give compilator.With abouve 32 KB may also occur problem . Choice MMU from Tools 
as 32 KB cache + 32 KB IRAM (balanced ). You can try other option 
de sp9auv
