### ISSUE TITLE
Support multiple storage backends (including SD card)

### ISSUE THREAD

**Issue by Avamander** [mysensors/MySensors#350]
I've seen EEPROM used by this library quite a bit. But would't a SD Card be a better idea, allowing more data to be stored, that data could be also modified by the PC and some things like atsha could be configured more securely by generating more random hmac for example.

**Comment by tbowmo** [comment]
I'm looking at adding micro SD card support to a new GW that will be
released as official hw later this year.

fre. 15. jan. 2016 19.12 skrev Avamander <notifications@github.com>:

**Comment by henrikekblad** [comment]
Creating different drivers for storage backends is a great idea, would simplify things if/when implementing RPI support as well.

MYStorageEEPROM
MyStorageSD
MyStorageFile (RPI)
etc

**Comment by tbowmo** [comment]
Will that be an extra layer on top of the SD card library? (as an example?)

lør. 6. feb. 2016 12.32 skrev Henrik Ekblad <notifications@github.com>:

**Comment by henrikekblad** [comment]
Not sure. Guess we'll need things move things out from the Hw to a  MYStorageEEPROM and make a similar (thin) driver for writing/reading from SD. Just a couple of methods (which calls the SD-library) as I can see it.

**Comment by tbowmo** [comment]
What if we have both eeprom and SD card?

lør. 6. feb. 2016 19.40 skrev Henrik Ekblad <notifications@github.com>:

**Comment by henrikekblad** [comment]
Then you'll have to choose where you want to store the routing/node information. I can't imagine you'd want to have it stored in EEPROM and SD card at the same time?
