### ISSUE TITLE
GatewaySerial not receiving data with MY_WITH_LEDS_BLINKING_INVERSE

### ISSUE THREAD

**Issue by Kolbi** [mysensors/MySensors#368]
I just tried to compile a GatewaySerial (https://github.com/mysensors/Arduino/blob/development/libraries/MySensors/examples/GatewaySerial/GatewaySerial.ino) with MY_WITH_LEDS_BLINKING_INVERSE enabled. It compiles but the Gateway can't receive any data, uncommenting this line and recompiling solve this issues. So it must be this function.
Thank you.

**Comment by mrred2k** [comment]
I just wanted to contribute here: I tried changing the pins for the 3 LEDS but the pinchange did not have any effect. Did not expierenced any problems compiling thought.

**Comment by tekka007** [comment]
@Kolbi Is this still an issue with 2.0.0?

**Comment by Kolbi** [comment]
@tekka007 good question :) haven't tested it since a while.

**Comment by sincze** [comment]
Mmm, I seem to suffer from a similar issue not with MY_WITH_LEDS_BLINKING_INVERSE but with MY_WITH_LEDS_BLINKING. The Serial Gateway 2.0.0. seems to sleep. Only after several triggers it awakes and the leds start flashing when i trigger a doorsensor.. Leaving serial gateway without activity for a while same results. I have to try to see if i can open 2 serial monitors that will monitor the serial gateway and the other one the sensor to see what exactly the logs will say.

**Comment by henrikekblad** [comment]
Fixed #640
