### ISSUE TITLE
RFM69_ATC: Automatic Transmission Control

### ISSUE THREAD

**Issue by trlafleur** [mysensors/MySensors#402]
should consider adding this feature to RFM69 radio driver...

from: http://lowpowerlab.com/blog/category/rfm69/

**Comment by trlafleur** [comment]
I have all this working now and have 7 devices on it to a serial gateway...
Using new (current) RFM69 driver and RFM69_ATC...
Its interesting to see the power levels change as packets flow...

If I can figure out how to do a PULL request, I will make it happen to 2.0b development branch...

tom

**Comment by LemarinelNet** [comment]
Isn't this already merged in 2.2.0 beta ?

**Comment by tekka007** [comment]
True!
