### ISSUE TITLE
Improve smartSleep: add a "no more commands" message to the gateway

### ISSUE THREAD

**Issue by abmantis** [mysensors/MySensors#468]
Currently, smartSleep() simply waits a specified amount of time for any command from the gateway.
Instead, after sending the heartbeat, the node could wait (with a timeout value) for a "no more commands" message from the gateway and sleep after receiving that. This would reduce the waiting time before sleeping.
Another improvement would be having a "request commands" from the node instead of the heartbeat.

So, on the node:
- Send "request commands"
- Wait until "no more commands" is received
- Sleep

On the gateway:
- "request commands" is received from a node
- Send commands to node
- Send "no more commands" message.

**Comment by MartinHjelmare** [comment]
This is good. I assume the gateway in the above description means the controller.

**Comment by tekka007** [comment]
see #722, use dedicated messages
