### ISSUE TITLE
esp8266 gateway will always start with DHCP

### ISSUE THREAD

**Issue by yoram-s** [mysensors/MySensors#516]
current code implementation will begin the wifi before the config has taken an affect. 
MyGatewayTransportEthernet.cpp 
`
		(void)WiFi.begin(MY_ESP8266_SSID, MY_ESP8266_PASSWORD);
		#ifdef MY_IP_ADDRESS
			WiFi.config(_ethernetGatewayIP, _gatewayIp, _subnetIp);
		#endif
`
The call should be reverse, first the config then the begin.

**Comment by tekka007** [comment]
Not really a bug, see the 4th paragraph in [WiFiConfig](https://www.arduino.cc/en/Reference/WiFiConfig):

> You can call WiFi.config() after WiFi.begin(), but the shield will initialize with begin() in the default DHCP mode. Once the config() method is called, it will change the network address as requested.

So, the current setup should also be fine, nevertheless, an upcoming PR will be addressed this.

Thanks for reporting.

**Comment by tekka007** [comment]
Please, feel free to test and provide feedback: https://github.com/tekka007/MySensors/tree/ChangeInitOrder
