### ISSUE TITLE
Typo in Keywords.txt and library api(MySensor.h)

### ISSUE THREAD

**Issue by rollercontainer** [mysensors/MySensors#521]
Hi 
shoudn't it be spelled with a "s" at the end?
https://www.mysensors.org/download/sensor_api_20
https://github.com/mysensors/MySensors/blob/development/keywords.txt

**Comment by henrikekblad** [comment]
We don't have the MySensor class any more so it should be removed entirely from keyworks.txt.

**Comment by rollercontainer** [comment]
But there is a Mysensors.h which is currently uncolored in the Arduino IDE.
