### ISSUE TITLE
Individual LEDs can't be enabled - now it's all or nothing

### ISSUE THREAD

**Issue by Yveaux** [mysensors/MySensors#562]
~~When a sketch defines MY_LEDS_BLINKING_FEATURE the MySensors library assumes MY_DEFAULT_xxx_LED_PIN are also defined.
When they are not, and MY_HW_xxx_LED_PIN are also not defined (https://github.com/mysensors/MySensors/blob/development/MySensors.h#L75) the LED blinking will silently fail.~~
Confused by forum post: https://forum.mysensors.org/topic/4569/ethernet-gateway-2-0-leds-don-t-blink
Apparently the defaults are 4,5,6 for non-ESP and 7,8,9 for ESP.

Furthermore, the library assumes that if one of the MY_DEFAULT_xxx_LED_PIN are defined, that all 3 LEDs are present and configured (https://github.com/mysensors/MySensors/blob/development/core/MyLeds.cpp#L40).
This may not be the case, and it should be possible to have e.g. only an error LED.

**Comment by Yveaux** [comment]
Conclusion after discussing:
- MY_HW_xxx_LED_PIN can be defined in variants (board specific) to automatically assign LED pins
- User should define any of MY_DEFAULT_xxx_LED_PIN in his sketch, when he wants to assign LEDs to MySensors
- MY_LEDS_BLINKING_FEATURE will be depricated, as defining one or more of MY_DEFAULT_xxx_LED_PIN will automatically enable LED blinking by the library.
- Example Gateway sketches must be extended with MY_DEFAULT_xxx_LED_PIN definitions, and MY_LEDS_BLINKING_FEATURE  should be removed (**add conversion notes to release notes for 2.0.1**)
- Refrain from falling back to some default led pins, when MY_DEFAULT_xxx_LED_PIN are not defined
- Individual LEDs can be enabled by defining just the MY_DEFAULT_xxx_LED_PIN - no longer all or nothing!

**Comment by GertSanders** [comment]
Like !
