### ISSUE TITLE
Rename MY_RADIO_FEATURE

### ISSUE THREAD

**Issue by tekka007** [mysensors/MySensors#568]
@fallberg commented (https://github.com/mysensors/MySensors/pull/558):
It appears MY_RADIO_FEATURE is used for all transport related code, so perhaps it should be renamed as it also include wire bound transport backends.

**Comment by henrikekblad** [comment]
Yeah, it was named before the introduction of RS485, doesn't make any sense today.

**Comment by henrikekblad** [comment]
MY_SUB_NETWORK/MY_VIRTUAL_NETWORK perhaps?

**Comment by tbowmo** [comment]
MY_SENSOR_NETWORK?

Den ons. 31. aug. 2016 09.13 skrev Henrik Ekblad <notifications@github.com>:
