### ISSUE TITLE
Default CSN/CE pins initialised if not used

### ISSUE THREAD

**Issue by tekka007** [mysensors/MySensors#576]
Issue reported:

https://forum.mysensors.org/topic/4671/arduino-d10-initialized-with-nrf-even-when-not-used-version-2-0-0-stable

Need to verify

**Comment by tbowmo** [comment]
It's a hardware limitation in the implementation of the SPI interface on atmega328p.

If SS is defined as input, and it goes low, then a master will automatically switch to slave mode.
(ref. atmega328 datasheet section 19.3.2)
