### ISSUE TITLE
Implement check connection and update status

### ISSUE THREAD

**Issue by pepeEL** [mysensors/MySensors#641]
Hi
I use on MySensors in Domoticz relays to switches light. One of the problem is...
When power is down ok all relays is OFF or ON (what i set in sketch).  This ok ok. But when client mysensors lost connection with gateway and then i change status on relays by phisical switch , then client connect to gateway it no update status in Domoticz. Still show status before lost connection with gateway. It is big problem... because when power down client start faster then start Domoticz on Raspberry with Gateway USB.

**Comment by henrikekblad** [comment]
Your node needs to send updates regularly to make this happen. There is no automatic send magic going on in the node.

**Comment by pepeEL** [comment]
But how do it ?

**Comment by pepeEL** [comment]
Please help me how i can do it ?
