### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by juan8taco** [mysensors/MySensors#650]
Hi, Can you add the following files to the core directory.
I'm working on a project with Arduino and Ikea Dioder and user used the files from
https://github.com/mysensors/MySensors
these files seem to be missing.
MyTransportNRF24.h
MySensor.h

**Comment by tbowmo** [comment]
I think that there is something wrong in your copy of the library. The files is not removed from the repository. 

Try including mysensors.h instead of mysensor.h 

If that fails, try reinstalling the mysensors library in arduino
