### ISSUE TITLE
Wrong packet length with enabled encryption

### ISSUE THREAD

**Issue by fbeek** [mysensors/MySensors#677]
Hello,

when i use the latest development version on my two node and enabled encryption i get the following error on the gateway: 

0;255;3;0;9;!TSF:MSG:LEN,16!=7 

Both nodes have the correct AES key (i checked it in with a debug statement) and before the update (last version was from may) everything worked fine.

If i disable the encryption everything is ok.  There i no power issue, because they where running without problems until now and i checked it twice. Signing is working also.

Regards 
fbeek

**Comment by fallberg** [comment]
And you have used the newer personalization routine so that the AES key is stored in EEPROM?

**Comment by fallberg** [comment]
(I am guessing you have done that if you have signing working, which require the same procedure)

**Comment by fbeek** [comment]
Hey.

Yes i used the newer one to personalize the nodes. The key where in the Memory. I added a serial output function to print the keys. They are the same on both devices.

**Comment by fallberg** [comment]
I have not used encryption more than testing it once for nrf24 and it worked back then when I moved the keys to eeprom. Which radio are you using?

**Comment by fbeek** [comment]
I use two normal NRF24, the ones without pa and lna.

**Comment by fallberg** [comment]
Ok, and no relay nodes used?

**Comment by fallberg** [comment]
Could you please try to add some debug to determine if the message sent has been encrypted at all or if it even attempts to decrypt it at the receiving end?

**Comment by fbeek** [comment]
Good Morning,

there is no relay node in use. As far as I debugged it yesterday, the package gets encrypted on the sender side and decrypted on gateway Side, both with the correct key.

**Comment by fallberg** [comment]
We have a clue to what's wrong. Expect some  ore details during the day.

**Comment by fbeek** [comment]
Thanks for your help.I stay tuned.

**Comment by fallberg** [comment]
@tekka007 has found a problem in the RF24 driver. It's being looked at. Thanks for reporting.

**Comment by fbeek** [comment]
Ok. Thanks for your great work on this project!
