### ISSUE TITLE
Test node to node communication in 2.1

### ISSUE THREAD

**Issue by tekka007** [mysensors/MySensors#692]
https://forum.mysensors.org/topic/5516/node-to-node-communnication-in-v2-0-between-repeater-nodes/4

**Comment by trlafleur** [comment]
any info on how this is going to work?? will we need changes in the gateway?? or is it all in the base code...

thanks

**Comment by tekka007** [comment]
ok, see forum thread for details:
`send(msgCustom.setSensor(64).set(0.121, 3).setDestination(8));`
