### ISSUE TITLE
Set channel in setup are

### ISSUE THREAD

**Issue by devilsray** [mysensors/MySensors#701]
Hi,

it would be great when it is possible to set the channel in the setup function. So i can define the channel by dip switches or jumpers or something else at startup

**Comment by devilsray** [comment]
would be also great when setting the client id in setup area will also be possible. At the moment there is no generic project possible. Every device needs a defined id to address them. The auto-id is not working for me, because after repowering them, the ids are changed.

**Comment by henrikekblad** [comment]
This is already possible. Use the same precipice as in this example for nodeId:
https://forum.mysensors.org/topic/5410/changing-node-id-at-run-time/5
