### ISSUE TITLE
getConfig() vs getControllerConfig()

### ISSUE THREAD

**Issue by brahmafear** [mysensors/MySensors#736]
MySensorsCore.h lists a function getControllerConfig() on line 207 - which is not defined in the .cpp file.  MySensorsCore.cpp defines a function getConfig() on line 265 - which is not defined in the .h file.  It would seem this is a typo and one entry should be changed to match the other.  Currently exists in both master and development branch.

**Comment by tekka007** [comment]
@brahmafear Good catch, thanks for reporting ;)
