### ISSUE TITLE
Separating driver libraries from the main repository

### ISSUE THREAD

**Issue by Avamander** [mysensors/MySensors#757]
Have you thought about separating the driver libraries from the main repository? This would allow people to fork certain libraries and keep them updated/modified themselves not having to fork entire MySensors. Even if some parts are MySensors specific.

**Comment by henrikekblad** [comment]
We currently don't have any plans of separating things from core at the moment. The main reason is the idiotic Arduino IDE, which doesn't have any type of dependency handling for libraries. And we would like the users of the library to be up and running without too much hassle.

Creating a separate release builder (picking different libraries and creating a bundle) was something we thought about earlier. But unfortunately we haven't got the bandwidth to do it right now.

Some of the included drivers already is separate projects and just lifted into MySensors for convenience to the end user (and to freeze a specific version).
