### ISSUE TITLE
Use MY_BAUD_RATE in SecurityPersonalizer

### ISSUE THREAD

**Issue by mfalkvidd** [mysensors/MySensors#758]
115200 is hardcoded in SecurityPersonalizer
https://github.com/mysensors/MySensors/blob/8e1ef13804f2737079298c63bd0d8aa7b82e7f73/examples/SecurityPersonalizer/SecurityPersonalizer.ino#L717

It would be better if the sketch used MY_BAUD_RATE since everything else uses that.

This problem was found in https://forum.mysensors.org/post/57874

**Comment by mfalkvidd** [comment]
This was fixed in https://github.com/mysensors/MySensors/pull/794
Closing.

**Comment by fallberg** [comment]
Thanks. I must have missed tagging this issue.
