### ISSUE TITLE
Dual gateway, MQTT and controller 

### ISSUE THREAD

**Issue by trlafleur** [mysensors/MySensors#760]
It's offen desirable to have a gateway support MQTT as well as normal controller function...
Data from MQTT or controller are sent on to the sensor, messages from the sensor are sent on to both.

Are there any restrictions in MySensor to prevent this?

Is their any help available to implement such a GW?

**Comment by henrikekblad** [comment]
This isn't anything we have in the development pipe at the moment.  Multiple radio transport layers like combining NRF24/RFM69 is closer.

It would mean that the gateway would have to keep multiple connections open to(or listen) depending on the client mode. One for each MQTT/MySensors controller connection. This is not possible in the current implementation.
