### ISSUE TITLE
V_HVAC_SETPOINT_COLD

### ISSUE THREAD

**Issue by derfloDev** [mysensors/MySensors#796]
Actually I'm not really sure if this is a issue.
But in MyMessage.h is a definition for "V_HVAC_SETPOINT_COOL". Then in the comment of S_HVAC it refers to "V_HVAC_SETPOINT_COLD".  And in the documentation on https://www.mysensors.org/download/serial_api_20 its the same problem. 
This really confused me. But seems to be a writing mistake.

**Comment by henrikekblad** [comment]
Thanks, 
V_HVAC_SETPOINT_COOL is the correct naming. I just updated the web page at will try to change it in MyMessage.h at some point.
