### ISSUE TITLE
Signing: personalizer sets the lock config flag for soft signing

### ISSUE THREAD

**Issue by mfalkvidd** [mysensors/MySensors#805]
This is shown in the output:
`Will not require UART confirmation before locking ATSHA204A configuration `

**Comment by fallberg** [comment]
@mfalkvidd Title is a bit misleading. The title suggest it is the lock config flag that is set, but your comment suggest it is the disabling of the UART configuration that is set.

**Comment by fallberg** [comment]
The solution to this bug is to rephrase the message. It is intentional to set the flags in all modes as they are automated, but the flag does not necessarily have to be ATSHA204A specific (although it currently is). This will be rephrased.
