### ISSUE TITLE
GatewayESP8266 won't compile when MY_USE_UDP is defined

### ISSUE THREAD

**Issue by RB3rg** [mysensors/MySensors#817]
From the GatewayESP8266 example when MY_USE_UDP mode is enabled and MY_IP_ADDRESS is defined errors will show up during the compilation at any arduino version.

The cause is a logical mistake in MySensors.h lines 145 and 148
Line 145: 
`#if defined(MY_CONTROLLER_IP_ADDRESS) || defined(MY_CONTROLLER_URL_ADDRESS)`
`#define MY_GATEWAY_CLIENT_MODE`

No, MY_GATEWAY_CLIENT_MODE can't be defined if MY_USE_UDP is enabled.
Replaced line 145 from: 
`#if  defined(MY_CONTROLLER_IP_ADDRESS) || defined(MY_CONTROLLER_URL_ADDRESS)`
To: 
`#if !defined(MY_USE_UDP) && (defined(MY_CONTROLLER_IP_ADDRESS) || defined(MY_CONTROLLER_URL_ADDRESS))`

Line 148: 
`#if defined(MY_USE_UDP) && !defined(MY_GATEWAY_CLIENT_MODE)`
`#error You must specify MY_CONTROLLER_IP_ADDRESS or MY_CONTROLLER_URL_ADDRESS for UDP`

Why this error message if  MY_CONTROLLER_IP_ADDRESS was enabled in the sketch?
Replace line 148 from:
`#if defined(MY_USE_UDP) && !defined(MY_GATEWAY_CLIENT_MODE)`
To:
`#if defined(MY_USE_UDP) && !defined(MY_GATEWAY_CLIENT_MODE) && !defined(MY_CONTROLLER_IP_ADDRESS)`

Now the sketch will compile without errors.

**Comment by marceloaqno** [comment]
You need to uncomment MY_CONTROLLER_URL_ADDRESS from the sketch as the error message suggest.
