### ISSUE TITLE
Fixing the code for use of: MY_USE_UDP & MY_CONTROLLER_IP_ADDRESS

### ISSUE THREAD

**Issue by RB3rg** [mysensors/MySensors#819]
Things was working in version 2.0.0 then someone re-wrote line 178 of MyGatewayTransportEthernet.cpp removing
`#if defined(MY_CONTROLLER_IP_ADDRESS) ` // version 2.0.0
and adding
`#if defined(MY_GATEWAY_CLIENT_MODE)` // version 2.1.1

Now the Gateway won't send the UDP data to the Controller.
To fix it you have to replace line 178 from MY_GATEWAY_CLIENT_MODE to MY_CONTROLLER_IP_ADDRESS like in version 2.0.0

Regarding to MY_USE_UDP please also see fix: #817 
I think I'm the only one using ESP8266 and UDP.

**Comment by mfalkvidd** [comment]
Hi.

I did some didding in git and found this https://github.com/mysensors/MySensors/commit/0c11354a2a9a0b67079b6c2723e9134923e1137a

It says "MY_USE_UDP requires that MY_GATEWAY_CLIENT_MODE is set."

If I understand correctly, all you need to do is to define MY_GATEWAY_CLIENT_MODE in your sketch. Could you try this?
