### ISSUE TITLE
STM32F1 OTA support?

### ISSUE THREAD

**Issue by mtiutiu** [mysensors/MySensors#822]
Hi,

I know that maybe is to early to ask for this but can we have OTA implemented for STM32F1 in the future? It will be a really great addition. Maybe the [existing](https://github.com/rogerclarkmelbourne/STM32duino-bootloader) stm32duino bootloader can be adapted to work with OTA. I found [here](https://github.com/rogerclarkmelbourne/STM32duino-bootloader/blob/master/updater_stm32f1/updater_stm32f1.ino) an example sketch for how to do flash write operations.

I know that this may be not a very easy task to do and I will be glad to help but unfortunately my software skills are not so great at the moment...but willing to learn.
I wanted to know if this feature is feasible at least on the STM32 MCU's. Thanks.

**Comment by Elektroman2** [comment]
Is there any progress in this topic? I am using Slober as IDE for mySensors development. Is that can work with OTA?
Thanks in advice, Marcell

**Comment by tekka007** [comment]
Certainly of interest, but postponed indefinitly due to limited resources. PRs are welcome!
