### ISSUE TITLE
[featurerequest] Wireless Gatway for wired network

### ISSUE THREAD

**Issue by pgollor** [mysensors/MySensors#825]
I would like to build a wired network with RS-485 based sensors, because wireless signals can't go through it. But outside of the metal house i can send and receive messages via NRF24L01.

So but the current MySensor library supports only a LAN, WLAN or serial gateway, but i need a NRF gateway. ;-)
Because there is no LAN or WLAN available. Would it possible to do this?
I think two ways could be useful:
1. a real gateway function
2. only pass through between RS-485 and NRF without an extra gateway

Which one would be easier to implement? I could help with this, but i don't exactly know the best point to start at. Allows the current library structure this modification?

**Comment by henrikekblad** [comment]
Please use the support forum for questions.
