### ISSUE TITLE
SecurityPersonalizer: 'EEPROM_PERSONALIZATION_CHECKSUM_ADDRESS' was not declared in this scope

### ISSUE THREAD

**Issue by SergioRius** [mysensors/MySensors#862]
Compiling SecurityPersonalizer.ino throws: 'EEPROM_PERSONALIZATION_CHECKSUM_ADDRESS' was not declared in this scope At line 467.

Relevant dump:
`...\SecurityPersonalizer\SecurityPersonalizer.ino: In function 'void write_eeprom_checksum()':

SecurityPersonalizer:695: error: 'EEPROM_PERSONALIZATION_CHECKSUM_ADDRESS' was not declared in this scope

  hwWriteConfigBlock((void*)&hash[0], (void*)EEPROM_PERSONALIZATION_CHECKSUM_ADDRESS, 1);`

Seems that this file is in a pre-release state, but it's the one referenced at the docs in the mysensors website, and the recommended at the forum.

**Comment by mfalkvidd** [comment]
@SergioRius which version/branch are you using?

**Comment by fallberg** [comment]
This is not a problem on the development branch at least. Please use that one for beta-firmware.

**Comment by SergioRius** [comment]
Sorry guys for the late answer, I've been very ill (still do).
Go to https://www.mysensors.org/about/signing#relevant-sketches and copy the SecurityPersonalizer sketch there.
Then fix the new lib error by replacing (at 40): "#include "sha204_lib_return_codes.h"" for "#include "sha204_includes/sha204_lib_return_codes.h"" as this is how the library is distributed.

Then just compile to get:
![eeprom_personalization_checksum_address](https://user-images.githubusercontent.com/1693727/26889864-d0dfd7de-4baf-11e7-935e-0ac041826144.png)

Perhaps an include is missing? <EEPROM.h>?
I've tried to fix it but still I don't understand well what's going on there.

**Comment by fallberg** [comment]
You can't just pick any ino file and compile it. You need to make sure you have the necessary libraries. And that the libraries are up2date and in sync with the expectations of the ino file.
In the case of EEPROM_PERSONALIZATION_CHECKSUM_ADDRESS, it is available on the development branch of the library, and it is defined [here](https://github.com/mysensors/MySensors/blob/development/core/MyEepromAddresses.h#L66).

**Comment by fallberg** [comment]
Regarding the references on the page, you are correct, and I have updated the references there.

**Comment by SergioRius** [comment]
I see we finally understood each other. Thanks. And sorry for the unconvenience.
