### ISSUE TITLE
NRF5 radio encryption is not working

### ISSUE THREAD

**Issue by d00616** [mysensors/MySensors#867]
After initializing two NRF5 via SecurityPersonalizer and enabling encryption both nodes cannot communicate. There are "!TSF:MSG:LEN,16!=7" messages.

The key is eqal on both nodes. The encryption code is taken from NRF24.

At the moment I have no idea about the reason.

**Comment by tekka007** [comment]
see here, did you adjust: https://github.com/mysensors/MySensors/blob/development/core/MyTransport.cpp#L649

**Comment by d00616** [comment]
@tekka007 Thank you. Now, it's working. I create a PR.

**Comment by tekka007** [comment]
Excellent 👍

**Comment by d00616** [comment]
PR: https://github.com/mysensors/MySensors/pull/868
