### ISSUE TITLE
Mysensor.h error

### ISSUE THREAD

**Issue by mask159874** [mysensors/MySensors#884]
C:\Users\Tone\Desktop\MySensors-1.5.4\libraries\MySensors\examples\LightSensor\LightSensor.ino:30:24: fatal error: MySensor.h: No such file or directory

Please help :(

**Comment by mfalkvidd** [comment]
It looks like you are trying to compile a sketch for MySensors 1.x. Is this your intention? What version of the library have you installed?

**Comment by mask159874** [comment]
Thank you!
