### ISSUE TITLE
Latest commits for nrf5 sleep() problem

### ISSUE THREAD

**Issue by rmtucker** [mysensors/MySensors#916]
The latest commits for nrf5 sleep() improvements have screwed it up.
A sleep of 10000  ms now only sleeps 326 ms.
Something wrong in there

**Comment by rmtucker** [comment]
Found the problem.

MY_HW_RTC->CC[0] = max((ms<<12 / 125), 2);

Should be:-

MY_HW_RTC->CC[0] = max(((ms << 12) / 125), 2));

in MyHwNRF5.cpp

**Comment by mfalkvidd** [comment]
This seems to be fixed by https://github.com/mysensors/MySensors/pull/917 ?

**Comment by rmtucker** [comment]
Yes fixed now.
