### ISSUE TITLE
Splash Screen can break backward compatibility

### ISSUE THREAD

**Issue by LemarinelNet** [mysensors/MySensors#930]
The splash-screen (included since #889) which is set ENABLED by default breaks the compatibility on my openhab binding:

It seems that the bindings always split the incoming frame with semi-column, but the splash lines doesn't contains the required semi-columns, and then the binding code (which is not robust enough) fails in a java unhandled error.

Would'nt it be more secure to output the splash-screen as a common frame (i.e. a comment or debug frame) ? 
Or at least, a more backward-compatible would be to set splash_screen DISABLED by default ?

**Comment by henrikekblad** [comment]
@tekka007, maybe the splash should be printed like normal debug messages on gateway-nodes so it doesn't interfere with the normal command parsing?

**Comment by LemarinelNet** [comment]
PS : @tekka007,Sorry for this off-topic, I've dropped you a message in mysensors forum about OTA ;) Have you seen it ?

**Comment by tekka007** [comment]
@hek This will most likely result in a distorted splash screen (due to the timer field).
I see two options: 
1. disable it if plugin has issues:
`#define MY_SPLASH_SCREEN_DISABLED
`
2. disable it on all GW nodes by default

**Comment by LemarinelNet** [comment]
I vote for a disabled by default behavior.
Having this enabled by default might get many users in trouble if they doesn't understand what's happening ;)

**Comment by henrikekblad** [comment]
@tekka, option 2 is probably best for backward compatibility.

**Comment by tekka007** [comment]
Fixed in #931
