### ISSUE TITLE
Parent static node,  but 255

### ISSUE THREAD

**Issue by andreypopov** [mysensors/MySensors#951]
I have 2 devices, they are in the same place (5meters from GW)

Sketch is the same, it starts like: 

**#define MY_DEBUG
#define MY_NODE_ID 31
#define MY_PARENT_NODE_ID 0
#define MY_PARENT_NODE_IS_STATIC 1**

**Here is log from 1st device:**
34 MCO:BGN:INIT NODE,CP=RNNNA---,VER=2.2.0-beta
53 TSM:INIT
56 TSF:WUR:MS=0
64 TSM:INIT:TSP OK
67 TSM:INIT:STATID=31
71 TSF:SID:OK,ID=31
74 TSM:FPAR
112 TSF:MSG:SEND,31-31-255-255,s=255,c=3,t=7,pt=0,l=0,sg=0,ft=0,st=OK:
2125 !TSM:FPAR:NO REPLY
2129 TSM:FPAR
2166 TSF:MSG:SEND,31-31-255-255,s=255,c=3,t=7,pt=0,l=0,sg=0,ft=0,st=OK:
4182 !TSM:FPAR:NO REPLY
4186 TSM:FPAR
4222 TSF:MSG:SEND,31-31-255-255,s=255,c=3,t=7,pt=0,l=0,sg=0,ft=0,st=OK:
6237 !TSM:FPAR:NO REPLY
6241 TSM:FPAR
6278 TSF:MSG:SEND,31-31-255-255,s=255,c=3,t=7,pt=0,l=0,sg=0,ft=0,st=OK:
8292 !TSM:FPAR:FAIL
8295 TSM:FAIL:CNT=1
8299 TSM:FAIL:DIS
8302 TSF:TDI:TSL
18306 TSM:FAIL:RE-INIT
18310 TSM:INIT
18318 TSM:INIT:TSP OK
18322 TSM:INIT:STATID=31
18326 TSF:SID:OK,ID=31
18330 TSM:FPAR
18368 TSF:MSG:SEND,31-31-255-255,s=255,c=3,t=7,pt=0,l=0,sg=0,ft=0,st=OK:
20381 !TSM:FPAR:NO REPLY
20385 TSM:FPAR

**And the 2nd:**
34 MCO:BGN:INIT NODE,CP=RNNNA---,VER=2.2.0-beta
53 TSM:INIT
56 TSF:WUR:MS=0
64 TSM:INIT:TSP OK
67 TSM:INIT:STATID=32
71 TSF:SID:OK,ID=32
74 TSM:FPAR
112 TSF:MSG:SEND,32-32-255-255,s=255,c=3,t=7,pt=0,l=0,sg=0,ft=0,st=OK:
830 TSF:MSG:READ,0-0-32,s=255,c=3,t=8,pt=1,l=1,sg=0:0
839 TSF:MSG:FPAR PREF
843 TSF:MSG:FPAR OK,ID=0,D=1
848 TSM:FPAR:OK
850 TSM:ID
852 TSM:ID:OK
856 TSM:UPL
860 TSF:MSG:SEND,32-32-0-0,s=255,c=3,t=24,pt=1,l=1,sg=0,ft=0,st=OK:1
871 TSF:MSG:READ,0-0-32,s=255,c=3,t=25,pt=1,l=1,sg=0:1
881 TSF:MSG:PONG RECV,HP=1
885 TSM:UPL:OK
888 TSM:READY:ID=32,PAR=0,DIS=1
930 !TSF:MSG:SEND,32-32-0-0,s=255,c=3,t=15,pt=6,l=2,sg=0,ft=0,st=NACK:0100
944 TSF:MSG:READ,0-0-32,s=255,c=3,t=15,pt=6,l=2,sg=0:0100
955 TSF:MSG:SEND,32-32-0-0,s=255,c=0,t=17,pt=0,l=10,sg=0,ft=1,st=OK:2.2.0-beta
973 TSF:MSG:SEND,32-32-0-0,s=255,c=3,t=6,pt=1,l=1,sg=0,ft=0,st=OK:0
3006 TSF:MSG:SEND,32-32-0-0,s=99,c=0,t=23,pt=0,l=0,sg=0,ft=0,st=OK:
3021 TSF:MSG:SEND,32-32-0-0,s=1,c=0,t=3,pt=0,l=0,sg=0,ft=0,st=OK:
3035 TSF:MSG:SEND,32-32-0-0,s=2,c=0,t=5,pt=0,l=0,sg=0,ft=0,st=OK:
3050 TSF:MSG:SEND,32-32-0-0,s=3,c=0,t=5,pt=0,l=0,sg=0,ft=0,st=OK:
3063 TSF:MSG:SEND,32-32-0-0,s=4,c=0,t=5,pt=0,l=0,sg=0,ft=0,st=OK:
3077 TSF:MSG:SEND,32-32-0-0,s=5,c=0,t=5,pt=0,l=0,sg=0,ft=0,st=OK:

Why MySensors try to send to 255-255
In 1st case - failed (No potential parents replied to find parent request)
In 2nd case - found correct 0-0 GW (Find parent response from node 0 is valid, distance 1 to GW)

**Comment by henrikekblad** [comment]
255 is the broadcast address. 

Please use the support forum at https://forum.mysensors org for general questions.
