### ISSUE TITLE
!RF24:INIT:SANCHK FAIL !TSM:INIT:TSP FAIL

### ISSUE THREAD

**Issue by jarnoburger** [mysensors/MySensors#967]
I am trying to start the nrf24 with a nano, but it doesn't want to.
I use an Arduino nano clone. connected (and powered) by USB to my laptop.
I installed the 2.1.1 library through the Arduino interface.
The nrf24 is the only device connected to the nano.

![image](https://user-images.githubusercontent.com/1609891/32268176-3ddd9342-beee-11e7-82ac-2ee80b5fbe6b.png)

**THIS IS MY PROBLEM :**

0 MCTO:BGN:INIT NODE,CP=RNNNA--,VER=2.1.1
3 TSM:INIT
4 TSF:WUR:MS=0
5 RF24:write register, reg=0, value=14
14 RF24:write register, reg=3, value=3
17 RF24:write register, reg=4, value=95
21 RF24:write register, reg=5, value=76
24 RF24:write register, reg=6, value=39
28 RF24:write register, reg=16, value=115
31 RF24:write register, reg=29, value=6
35 RF24:read register, reg=6, value=0
38 RF24:read register, reg=5, value=255
43 !RF24:INIT:SANCHK FAIL
45 !TSM:INIT:TSP FAIL
47 TSM:FAIL:CNT=1
48 TSM:FAIL:PDT
50 RF24:write register, reg=0, value=12
53 RF24:PD

All the other read registers look random.

**Comment by henrikekblad** [comment]
Please use the support forum at https://forum.mysensors.org for general help.
