### ISSUE TITLE
Problem compiling mysgw on rpi3 

### ISSUE THREAD

**Issue by tchoblond59** [mysensors/MySensors#980]
Hi !

Seems like the same issue in #955 
When i try to compile from development branch i get this error
 `drivers/BCM/bcm2835.c: In function ‘bcm2835_delayMicroseconds’:
drivers/BCM/bcm2835.c:441:40: error: expected ‘)’ before ‘PRIu64’
   printf("bcm2835_delayMicroseconds %" PRIu64 "\n", micros);`

I am running a fresh raspbian 9.1. I also try `./configure --extra-cxxflags="-DMY_DEBUG -D__STDC_FORMAT_MACROS"`

gcc version 6.3.0 20170516 (Raspbian 6.3.0-18+rpi1)

Am i missing something ?

Thanks

**Comment by res1mp7q** [comment]
Same issue here running dev version 
error: expected ‘)’ before ‘PRIu64’
   printf("bcm2835_delayMicroseconds %" PRIu64 "\n", micros);

**Comment by mfalkvidd** [comment]
@res1mp7q are you using the same gcc and rasbian versions as @tchoblond59 ?

**Comment by MissionWebUK** [comment]
I'm running on a rpi3 model B fresh install of raspbian stretch lite: 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux

Master branch had issues communicating with the nrf24 so I moved to dev branch. Same error as above but I didn't run the configure command that tchoblond59 ran, just the standard ethernet config

**Comment by mfalkvidd** [comment]
Forum threads on this subject:
https://forum.mysensors.org/topic/7944/rpi-gateway-tsm-init-tsp-fail/7
https://forum.mysensors.org/topic/7955/can-t-get-past-first-base-arduino-serial-gateway/8

**Comment by mfalkvidd** [comment]
Fix merged to development, will be included in upcoming 2.2.0 release
