### ISSUE TITLE
ESP8266 GW - nRF24 LmacRxBlk:1 periodic hovering gateway.

### ISSUE THREAD

**Issue by devicter** [mysensors/MySensors#991]
Under the stress-test, the lock periodically stops.
The latest library is used 2.2.0
I am ready together if there are those wishing to conduct an experiment.
The error is quite important, because does not allow the stable use of this equipment.

LmacRxBlk:1 
LmacRxBlk:1 
LmacRxBlk:1 
IP: 192.168.0.15
2209653 Attempting MQTT connection...
2209767 MQTT connected

branch of the forum
https://forum.mysensors.org/topic/4882/solved-wifi-gateway-crashing-20min

**Comment by tekka007** [comment]
Issue seems espressif SDK related (prior 2.4.0?). See https://github.com/Links2004/arduinoWebSockets/issues/12 and comments
